name: Run resign Script

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Name of the repo owner'
        required: true
      repo:
        description: 'Name of the repository'
        required: true

jobs:
  resign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Install GPG
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg

    - name: Build and run Go script
      run: |
        OWNER="${{ github.event.inputs.owner"
        REPO="${{ github.event.inputs.repo}}"

        cmd="cd go/sign;go mod tidy;go run main.go"

        if [ -n "$OWNER" ]; then
            cmd="$cmd -org \"$OWNER\""
        fi
        if [ -n "$REPO" ]; then
            cmd="$cmd -org \"$REPO\""
        fi

        eval $cmd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PAT: ${{ secrets.GH_PAT }}
        GPG_FINGERPRINT: ${{ secrets.GPG_PRIVATE_KEY }}
